project:
  type: website

website:
  title: "tquarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - test.ipynb

format:
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
  ipynb: 
    output-ext: output_foo.ipynb



