name: test
on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.92/quarto-1.2.92-macos.pkg
          sudo installer -allowUntrusted -pkg "quarto-1.2.92-macos.pkg" -target /
      - name: test preview
        run: |
          quarto -V
          quarto preview
