name: test
on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Quarto
        run: |
          wget $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/macos.pkg)
          sudo installer -allowUntrusted -pkg "macos.mpkg" -target /
      - name: test preview
        run: |
          quarto -V
          quarto preview
