name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Quarto
        run: |
          wget $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/macos.pkg)
          dpkg -i quarto*.deb
      - name: test preview
        run: |
          quarto -V
          quarto preview
